name: Android CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  # Điều chỉnh cho dự án của bạn nếu cần
  ANDROID_COMPILE_SDK: 34
  ANDROID_BUILD_TOOLS: 34.0.0
  NDK_VERSION: 25.2.9519653   # repo này có native code ⇒ bật NDK
  CMAKE_VERSION: 3.22.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Install Android SDK / Build-Tools / NDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-${{ env.ANDROID_COMPILE_SDK }}
            build-tools;${{ env.ANDROID_BUILD_TOOLS }}
            ndk;${{ env.NDK_VERSION }}
            cmake;${{ env.CMAKE_VERSION }}

      # Nếu dự án dùng wrapper, lệnh dưới là đủ. (Repo này có gradlew)
      - name: Build Debug
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Build Release (unsigned)
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            **/build/outputs/apk/debug/*.apk

      - name: Upload release APK (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: |
            **/build/outputs/apk/release/*.apk

      - name: Upload ProGuard/R8 mapping (nếu có)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mapping-files
          path: |
            **/build/outputs/mapping/release/mapping.txt
          if-no-files-found: ignore
