name: Android CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  ANDROID_COMPILE_SDK: 33
  ANDROID_BUILD_TOOLS: 33.0.2
  NDK_VERSION: 25.2.9519653
  CMAKE_VERSION: 3.22.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle (with cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Install Android SDK / Build-Tools / NDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-${{ env.ANDROID_COMPILE_SDK }}
            build-tools;${{ env.ANDROID_BUILD_TOOLS }}
            ndk;${{ env.NDK_VERSION }}
            cmake;${{ env.CMAKE_VERSION }}

      - name: Build Debug APK
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Build Release APK (unsigned)
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            **/build/outputs/apk/debug/*.apk

      - name: Upload Release APK (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: |
            **/build/outputs/apk/release/*.apk

      - name: Upload ProGuard / Mapping files (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mapping-files
          path: |
            **/build/outputs/mapping/release/mapping.txt
          if-no-files-found: ignore
